  # -----------------------------------------------------------------------
  # 2 ‚Äî Syst√®mes & R√©seaux (sp√©cialis√© infra)
  # -----------------------------------------------------------------------
  {"Syst√®mes & R√©seaux" = [
    "sys-reseau/index.md",

  #     {"Linux" = [
  #         "sys-reseau/linux/index.md",
  #         {"Administration"     = "sys-reseau/linux/admin.md"},
  #         {"Services & Daemons" = "sys-reseau/linux/services-daemons.md"},
  #         {"üìÅ S√©curit√© (host)"           = [
  #             "sys-reseau/linux/security/index.md",
  #             {"fail2ban"   = "sys-reseau/linux/security/fail2ban.md"},
  #             {"ufw"        = "sys-reseau/linux/security/ufw.md"},
  #             {"ClamAV"     = "sys-reseau/linux/security/clamav.md"},
  #             {"Lynis"      = "sys-reseau/linux/security/lynis.md"},
  #             {"Chkrootkit" = "sys-reseau/linux/security/chkrootkit.md"},
  #         ]},
  #     ]},

  #     {"Windows" = [
  #         "sys-reseau/windows/index.md",
  #         {"AD & GPO"     = "sys-reseau/windows/ad-gpo.md"},
  #         {"Durcissement" = "sys-reseau/windows/hardening.md"}
  #     ]},

  #     {"R√©seaux" = [
  #         "sys-reseau/network/index.md",
  #         {"üìÅ Outils & Analyse" = [
  #             "sys-reseau/network/outils/index.md",
  #             {"tcpdump"  = "sys-reseau/network/outils/tcpdump.md"},
  #             {"netstat"  = "sys-reseau/network/outils/netstat.md"},
  #             {"scapy"    = "sys-reseau/network/outils/scapy.md"},
  #             {"nslookup" = "sys-reseau/network/outils/nslookup.md"}
  #         ]},
  #         {"üìÅ Services r√©seau" = [
  #             "sys-reseau/network/services/index.md",
  #             {"SSH"    = "sys-reseau/network/services/ssh.md"},
  #             {"FTP"    = "sys-reseau/network/services/ftp.md"},
  #             {"DNS"    = "sys-reseau/network/services/dns.md"},
  #             {"Samba"  = "sys-reseau/network/services/samba.md"},
  #             {"LDAP & PAM" = "sys-reseau/network/services/ldap-pam.md"}
  #         ]},
  #         {"üìÅ S√©curit√© p√©rim√©trique" = [
  #             "sys-reseau/network/security/index.md",
  #             {"pfSense"  = "sys-reseau/network/security/pfsense.md"},
  #             {"WAF"      = "sys-reseau/network/security/waf.md"},
  #             {"OpenVPN"  = "sys-reseau/network/security/openvpn.md"},
  #             {"HAProxy"  = "sys-reseau/network/security/haproxy.md"}
  #         ]}
  #     ]},

  #     {"Virtualisation (HyperV.)" = [
  #         "sys-reseau/virtualisation/index.md",
  #         {"Panorama Virtualisation"      = "sys-reseau/virtualisation/panorama-hyperviseurs.md"},
  #         {"KVM / Proxmox"                = "sys-reseau/virtualisation/kvm-proxmox.md"},
  #         {"QEMU"                         = "sys-reseau/virtualisation/qemu.md"}
  #     ]},

  #     {"Stockage & Sauvegarde" = [
  #         "sys-reseau/storage/index.md",
  #         {"RAID & Filesystems" = "sys-reseau/storage/raid-fs.md"},
  #         {"Sauvegarde & PRA"   = "sys-reseau/storage/backup-pra.md"},
  #         {"Amanda (Backup)"    = "sys-reseau/storage/amanda.md"},
  #     ]},

  #     {"Supervision" = [
  #         "sys-reseau/observabilite/index.md",
  #         {"Logs & Journaux"   = "sys-reseau/observabilite/logs.md"},
  #         {"Monitoring (intro)"= "sys-reseau/observabilite/monitoring.md"},
  #         {"ntop/ntopng"       = "sys-reseau/observabilite/ntop.md"}
  #     ]},
  ]},