  # -----------------------------------------------------------------------
  # 3 â€” DÃ©veloppement & Cloud
  # -----------------------------------------------------------------------
  "DÃ©veloppement & Cloud" = [
    "dev-cloud/index.md",

  #     {"Langages" = [
  #         "dev-cloud/lang/index.md",
  #         {"ğŸ“ Python"     = [
  #             "dev-cloud/lang/python/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/python/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/python/avance.md"}
  #         ]},
  #         {"ğŸ“ JavaScript" = [
  #             "dev-cloud/lang/js/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/js/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/js/avance.md"}
  #         ]},
  #         {"ğŸ“ TypeScript" = [
  #             "dev-cloud/lang/ts/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/ts/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/ts/avance.md"}
  #         ]},
  #         {"ğŸ“ PHP" = [
  #             "dev-cloud/lang/php/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/php/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/php/avance.md"}
  #         ]},
  #         {"ğŸ“ Go" = [
  #             "dev-cloud/lang/go/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/go/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/go/avance.md"}
  #         ]},
  #         {"ğŸ“ Bash" = [
  #             "dev-cloud/lang/bash/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/bash/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/bash/avance.md"}
  #         ]},
  #         {"ğŸ“ Angular" = [
  #             "dev-cloud/lang/angular/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/angular/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/angular/avance.md"}
  #         ]},
  #         {"ğŸ“ Laravel" = [
  #             "dev-cloud/lang/laravel/index.md",
  #             {"Fondamentaux" = "dev-cloud/lang/laravel/fondamentaux.md"},
  #             {"AvancÃ©"       = "dev-cloud/lang/laravel/avance.md"}
  #         ]},
  #     ]},

  #     {"Stacks" = [
  #         "dev-cloud/frameworks/index.md",
  #         {"ğŸ“ MEAN" = ["dev-cloud/frameworks/mean/index.md"]},
  #         {"ğŸ“ TALL" = ["dev-cloud/frameworks/tall/index.md"]},
  #     ]},

  #     {"Architecture & API" = [
  #         "dev-cloud/architecture/index.md",
  #         {"API REST"           = "dev-cloud/architecture/api-rest.md"},
  #         {"Clean Architecture" = "dev-cloud/architecture/clean-architecture.md"},
  #         {"Patterns dâ€™architecture (pratique)" = "dev-cloud/architecture/patterns-pratiques.md"},
  #     ]},

  #     {"ğŸ“ Data" = [
  #         "dev-cloud/data/index.md",
  #         {"MariaDB & MySQL"  = "dev-cloud/data/sql.md"},
  #         {"NoSQL"            = "dev-cloud/data/nosql.md"},
  #         {"GraphQL"          = "dev-cloud/data/graphql.md"},
  #         {"SQLite"           = "dev-cloud/data/sqlite.md"}
  #     ]},

  #     {"Cloud Providers" = [
  #         "dev-cloud/cloud/index.md",
  #         {"AWS"   = "dev-cloud/cloud/aws/index.md"},
  #         {"Azure" = "dev-cloud/cloud/azure/index.md"}
  #     ]},

  #     {"Tests & QualitÃ©" = [
  #         "dev-cloud/tests-qualite/index.md",
  #         {"TDD"                     = "dev-cloud/tests-qualite/tdd.md"},
  #         {"Unitaires & IntÃ©gration" = "dev-cloud/tests-qualite/unit-integ.md"},
  #         {"Contrats & E2E"          = "dev-cloud/tests-qualite/contrats-e2e.md"}
  #     ]},
  ]},