  # -----------------------------------------------------------------------
  # 4 ‚Äî DevSecOps (pipeline, IaC, AppSec)
  # -----------------------------------------------------------------------
  {"DevSecOps" = [
    "devsecops/index.md",

  #     {"Culture & Pratiques" = [
  #         "devsecops/culture/index.md",
  #         {"CALMS (piliers DevOps)" = "devsecops/culture/calms.md"}
  #     ]},

  #     {"CI/CD" = [
  #         "devsecops/cicd/index.md",
  #         {"GitHub Actions" = "devsecops/cicd/github-actions.md"},
  #         {"GitLab CI/CD"   = "devsecops/cicd/gitlab-cicd.md"},
  #         {"Jenkins"        = "devsecops/cicd/jenkins.md"}
  #     ]},

  #     {"IaC & Automatisation" = [
  #         "devsecops/iac/index.md",
  #         {"Terraform / OpenTofu" = "devsecops/iac/terraform.md"},
  #         {"Ansible"              = "devsecops/iac/ansible.md"}
  #     ]},

  #     {"Conteneurs & Orchestration" = [
  #         "devsecops/containers/index.md",
  #         {"üìÅ Docker" = [
  #             {"Docker (Moteur)"         = "devsecops/containers/docker/docker.md"},
  #             {"Docker Compose"          = "devsecops/containers/docker/compose.md"},
  #             {"Docker Swarm"            = "devsecops/containers/docker/swarm.md"},
  #             {"Tableau comparatif (Docker/Compose/Swarm)" = "devsecops/containers/docker/tableau-comparatif.md"},
  #         ]},
  #         {"Kubernetes"              = "devsecops/containers/kubernetes.md"},
  #         {"Helm"                    = "devsecops/containers/helm.md"}
  #     ]},

  #     {"S√©curit√© Applicative" = [
  #         "devsecops/appsec/index.md",
  #         {"AuthN/AuthZ & JWT"  = "devsecops/appsec/jwt-auth.md"},
  #         {"SAST"               = "devsecops/appsec/sast.md"},
  #         {"DAST"               = "devsecops/appsec/dast.md"},
  #         {"SCA (d√©pendances)"  = "devsecops/appsec/sca.md"},
  #         {"Rate Limiting & RBAC" = "devsecops/appsec/rate-rbac.md"}
  #     ]},

  #     {"Secrets & Vault" = [
  #         "devsecops/secrets/index.md",
  #         {"Vault (HashiCorp)" = "devsecops/secrets/vault.md"}
  #     ]},

  #     {"Observabilit√© & S√©curit√©" = [
  #         "devsecops/obs-sec/index.md",
  #         {"Int√©grations IDS/IPS"     = "devsecops/obs-sec/ids-hooks.md"},
  #         {"Wazuh dans le pipeline"   = "devsecops/obs-sec/wazuh.md"}
  #     ]},
  ]},