  # -----------------------------------------------------------------------
  # 6 â€” Glossaire
  # -----------------------------------------------------------------------
  {"Glossaire" = [
    "glossaire/index.md",
  ]},
  
  # --------------------------------------------------------------------------
  # Fin de la navigation principale
  # --------------------------------------------------------------------------
]
