# ===========================================================================
  # 9 — Projets
  # ===========================================================================
  # Création de différents projet
  # ===========================================================================
  {"Projets" = [
    {"Lab Arch" = [
      "projets/arch-lab/index.md",
      {"introduction"           = "projets/arch-lab/01-introduction.md"},
      {"Panorama"               = "projets/arch-lab/02-panorama-linux.md"},
      {"Arch Serveur"           = "projets/arch-lab/03-arch-serveur.md"},
      {"Arch Desktop"           = "projets/arch-lab/04-arch-desktop.md"},
      {"Virtualbox - Réseau"    = "projets/arch-lab/05-virtualbox-reseau.md"},
      {"Lab multi-os"           = "projets/arch-lab/06-lab-multi-os.md"},
      {"Annexes"                = "projets/arch-lab/07-annexes.md"},
    ]}
  ]}

]